### PR TITLE
insert_deduplication_token setting for INSERT statement

### PR DESCRIPTION
**Pull request by devcrafter**
The setting allows a user to provide own deduplication semantic in Replicated*MergeTree
If provided, it's used instead of data digest to generate block ID
So, for example, by providing a unique value for the setting in each INSERT statement,
user can avoid the same inserted data being deduplicated

Issue: #7461

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

`insert_deduplication_token` setting for `INSERT` statement (only for `Replicated*MergeTree` tables)
The setting allows a user to provide own deduplication semantic in `Replicated*MergeTree`
For example, by providing a unique value for the setting in each INSERT statement,
the user can avoid the same inserted data being deduplicated

Detailed description / Documentation draft:
...

> By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

> If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by devcrafter** [comment]
I'd consider limiting the size of `insert_deduplication_token`. What could be a reasonable number? I guess 1 KB should be fine ...

**Comment by alexey-milovidov** [comment]
Not necessary, it is limited implicitly nevertheless by memory limit and other limits.

**Comment by devcrafter** [comment]
https://github.com/ClickHouse/ClickHouse/pull/31609#discussion_r753867597
https://github.com/ClickHouse/ClickHouse/pull/31609#discussion_r753867826

Done

**Comment by devcrafter** [comment]
@alesapin @alexey-milovidov Please let me know if you have any comments

**Pull request merged**
